name: update_LeetCodemd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: 1.17

    - name: Run
      run: |
        cd ${GITHUB_WORKSPACE}/LeetCode
        go run catagenerator.go

    - name: 🚀 Deploy
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Updata dynamic LeetCode.md :boom: "
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
